### ISSUE TITLE
[PE-D][Tester C] Cannot add person to module

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T10-1/tp#128]
![Screenshot 2022-10-28 at 4.35.09 PM.png](https://raw.githubusercontent.com/jamietan2002/ped/main/files/3c4420e5-ac5e-4742-9d2c-b79e88c6858e.png)
david li is displayed on screen but cannot be added to module

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: jamietan2002/ped#1

**Comment by cheeheng** [comment]
Closed because name is case-sensitive, same issue as #124
