### ISSUE TITLE
[PE-D][Tester C] Cannot view list of persons tagged to a module

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T10-1/tp#145]
![Screenshot 2022-10-28 at 5.16.09 PM.png](https://raw.githubusercontent.com/jamietan2002/ped/main/files/b5b001de-c509-48cc-ae53-1bd965b99fe6.png)

navigated to module page but list of person does not update

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: jamietan2002/ped#5

**Comment by cheeheng** [comment]
Not a bug? Did you use `find-module` instead of `goto`?
