### ISSUE TITLE
Tips from CS2101 UG consultation

### ISSUE THREAD

**Issue by teoyuqi** [AY2223S1-CS2103T-T10-1/tp#174]
Tips from Aileen
* [x] Have "modules, contacts, links, tasks" in the user description -> anyone
* [x] Include `Help` section -> jr
* [x] Clearer description of target audience (+fix CS students to students) -> same person as number 1
* [x] Label the GUI components (command box, etc.) -> we need to decide
* [ ] Explain (either include in glossary + link or explain in-situ) -> each add own word
  * [x] symbols of the "boxes" in how to use section -> yuqi 
  * [x] parameters -> chee heng
  * [ ] prefixes/flags -> wr
  * [x] alias -> shiwen decide to put in glossary or own section (just one)
* [x] Reduce technical/complicated terms (e.g., parameters, prefixes/flags, alias, etc.) if possible
  * Articulate design decisions 
* [x] Use clearer examples ("Complete assignment for week 7" vs "Complete W07 tP blah blah") -> everyone
* [x] Label the screenshots (to draw user's attention to specific components) -> everyone
* [x] The div box should state "you" instead of "users" -> jiarong 
* [x]  Numbering of quick start -> chee heng
* [x]  How to use guide -> anyone
* [x]  screenshots for all commands, and with labeling -> everyone

**Comment by cheeheng** [comment]
The last task is related to #147

**Comment by cheeheng** [comment]
Parameters were already defined in the first bulleted point - somehow it was missed
