### ISSUE TITLE
Ensure all classes and methods implemented have actual usages 

### ISSUE THREAD

**Issue by ekweirui** [AY2223S1-CS2103T-T10-1/tp#67]
Submitting an issue as a future reminder for us to close before we wrap up our project.

In the finalizing stage of our project, ensure that every class and method in it has an actual usage and is not unused. If unused, we should delete it (if appropriate) from the code base to reduce the potential for bugs and to reduce code complexity.

**Comment by cheeheng** [comment]
Closed as v1.4 code released
